name: Next.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20 # Use your Node.js version

      - name: Install dependencies
        run: npm install # or yarn install

      - name: Lint code
        run: npm run lint # Checks ESLint errors

      - name: Build project
        run: npm run build # Ensures Next.js builds without errors
